[package]
name = "texttoepub"
version = "0.1.0"
authors = ["chengpengfei <hoolooday@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"
epub-builder = "0.4.4"
encoding_rs = "0.8.22"